<?php

?>

<p style="text-align:center;font-weight:bold;">
	REDCap&trade; Shared Data Instrument Library (SDIL)<br>
	<u>Shared Content Agreement</u>
</p>

<p>
	By uploading your instrument to the REDCap&trade; Shared Data Instrument Library ("REDCap SDIL") hosted by Vanderbilt University ("Vanderbilt"), you signify your agreement to the terms of this Shared Content Agreement ("Agreement").
</p>

You:
<ul>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>Represent, acknowledge and agree that the content (including, but not limited to, instruments) uploaded by you ("Content") does not infringe on the intellectual property rights (including, but not limited to, copyrights) of any other person or entity and you affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish Content you submit.</i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>Shall be solely responsible for the Content and the consequences of submitting and publishing the Content on the REDCap SDIL website. </i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>Retain all ownership rights in the Content. However, by submitting Content to the REDCap SDIL website, you hereby grant to Vanderbilt a worldwide, non-exclusive, royalty-free, sublicense-able and transferable license to use, reproduce, distribute, display, and perform the Content in connection with the REDCap SDIL website's (and its successors' and affiliates') purposes. </i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>Grant to each user of the REDCap SDIL website a non-exclusive license to access your Content through the REDCap SDIL website and to use, reproduce, distribute, display and perform such Content as permitted under this Agreement. The above licenses in the Content granted by you terminate within a commercially reasonable time after you remove or delete your Content from the REDCap SDIL website. You understand and agree, however, that Vanderbilt may retain, but not display, distribute or perform, server copies of your Content that has been removed or deleted.</i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>Vanderbilt may, in its sole and absolute discretion, terminate your access to the REDCap SDIL website if it determines, in its sole and absolute discretion, that you are an infringer. Vanderbilt reserves the right to decide whether Content violates the terms of this Agreement or any other agreement between the parties at any time and may, without prior notice and in its sole and absolute discretion, remove such Content and/or terminate your access to the REDCap SDIL website.</i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>Agree to waive, and hereby do waive, any legal or equitable rights or remedies you have or may have against Vanderbilt with respect to the subject matter of this Agreement.</i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>To the extent permitted by applicable law, agree to indemnify and hold harmless Vanderbilt and its trustees, officers, directors, employees, affiliates, licensors, and licensees to the fullest extent allowed by law regarding all matters related to your use of the REDCap SDIL website or this Agreement. </i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>AGREE THAT YOUR USE OF THE REDCap SDIL WEBSITE SHALL BE AT YOUR SOLE RISK. TO THE FULLEST EXTENT PERMITTED BY LAW, VANDERBILT AND ITS TRUSTEES, OFFICERS, DIRECTORS, EMPLOYEES, AND AGENTS DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, IN CONNECTION WITH THE REDCap SDIL WEBSITE AND YOUR USE THEREOF. VANDERBILT MAKES NO WARRANTIES OR REPRESENTATIONS ABOUT THE ACCURACY OR COMPLETENESS OF THE REDCap SDIL WEBSITE AND ASSUMES NO LIABILITY OR RESPONSIBILITY FOR ANY (I) ERRORS, MISTAKES, OR INACCURACIES OF CONTENT, (II) PERSONAL INJURY OR PROPERTY DAMAGE, OF ANY NATURE WHATSOEVER, RESULTING FROM YOUR ACCESS TO AND USE OF THE REDCap SDIL WEBSITE, (III) ANY UNAUTHORIZED ACCESS TO OR USE OF OUR SECURE SERVERS AND/OR ANY AND ALL PERSONAL INFORMATION AND/OR FINANCIAL INFORMATION STORED THEREIN, (IV) ANY INTERRUPTION OR CESSATION OF TRANSMISSION TO OR FROM OUR SERVICES, (IV) ANY BUGS, VIRUSES, TROJAN HORSES, OR THE LIKE WHICH MAY BE TRANSMITTED TO OR THROUGH THE REDCap SDIL WEBSITE BY ANY THIRD PARTY, AND/OR (V) ANY ERRORS OR OMISSIONS IN ANY CONTENT OR FOR ANY LOSS OR DAMAGE OF ANY KIND INCURRED AS A RESULT OF THE USE OF ANY CONTENT POSTED, EMAILED, TRANSMITTED, OR OTHERWISE MADE AVAILABLE VIA THE REDCap SDIL WEBSITE. </i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>This Agreement is governed by the laws of the State of Tennessee, without respect to its conflict of laws principles. Any claim or dispute between you and Vanderbilt that arises in whole or in part from use of the REDCap SDIL website Service shall be decided exclusively by a court of competent jurisdiction located in Davidson County, Tennessee. This Agreement shall constitute the entire agreement between you and Vanderbilt regarding the subject matter herein. If any provision of this Agreement is deemed invalid by a court of competent jurisdiction, the invalidity of such provision shall not affect the validity of the remaining provisions of this Agreement, which shall remain in full force and effect. No waiver of any term of this Agreement shall be deemed a further or continuing waiver of such term or any other term, and Vanderbilt's failure to assert any right or provision under this Agreement shall not constitute a waiver of such right or provision. Vanderbilt reserves the right to amend this Agreement at any time and without notice. Your use of the REDCap SDIL website following any amendment of this Agreement will signify your assent to and acceptance of its revised terms. </i></li>
	<li class="column" style="list-style-type:initial;background:white;margin-left:20px;"><i>AND VANDERBILT AGREE THAT ANY CAUSE OF ACTION ARISING OUT OF OR RELATED TO THIS AGREEMENT MUST COMMENCE WITHIN ONE (1) YEAR AFTER THE CAUSE OF ACTION ACCRUES.  OTHERWISE, SUCH CAUSE OF ACTION IS PERMANENTLY BARRED.</i></li>
</ul>
